"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("./window/window");
require("./window/menu");
require("./permissions");
require("./store");
require("./dialog");
require("./shortcuts");
require("./about");
require("./window/contextMenu");
